# Generated by Django 4.1.5 on 2023-03-29 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bandwidth', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstrateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubstrateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bandwidth', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_substrate_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='base.substratenode')),
                ('target_substrate_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='base.substratenode')),
            ],
        ),
        migrations.CreateModel(
            name='Mapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logical_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.logicallink')),
                ('substrate_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.substratelink')),
            ],
        ),
        migrations.CreateModel(
            name='LogicalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('virtual_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.virtualnetwork')),
            ],
        ),
        migrations.AddField(
            model_name='logicallink',
            name='source_logical_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='base.logicalnode'),
        ),
        migrations.AddField(
            model_name='logicallink',
            name='substrate_links',
            field=models.ManyToManyField(through='base.Mapping', to='base.substratelink'),
        ),
        migrations.AddField(
            model_name='logicallink',
            name='target_logical_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='base.logicalnode'),
        ),
        migrations.AddField(
            model_name='logicallink',
            name='virtual_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.virtualnetwork'),
        ),
    ]
