# Generated by Django 4.1.5 on 2023-03-29 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalnode',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='logicalnode',
            name='substrate_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.substratenode'),
        ),
    ]
